// <auto-generated />
using Blazor26.DataAccess.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor26.DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260501191728_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor26.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Desktops"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Printers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Display Tables"
                        });
                });

            modelBuilder.Entity("Blazor26.Models.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Name = "HP PRo",
                            Price = 892.99f,
                            description = "Big desktop PC"
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Name = "Dell X100",
                            Price = 140.99f,
                            description = "Not a laptop"
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 2,
                            Name = "HP 450x",
                            Price = 1200.99f,
                            description = "bad colour printer"
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 2,
                            Name = "HP Meezie",
                            Price = 12500.99f,
                            description = "Good colour printer"
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 3,
                            Name = "Gala Table",
                            Price = 12123.99f,
                            description = "Very Big Table"
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 3,
                            Name = "DreamTop",
                            Price = 900.99f,
                            description = "Big Table"
                        });
                });

            modelBuilder.Entity("Blazor26.Models.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("SalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MonthName = "January",
                            ProductID = 1,
                            SalesAmount = 1200m
                        },
                        new
                        {
                            Id = 2,
                            MonthName = "February",
                            ProductID = 1,
                            SalesAmount = 1300m
                        },
                        new
                        {
                            Id = 3,
                            MonthName = "March",
                            ProductID = 1,
                            SalesAmount = 1400m
                        },
                        new
                        {
                            Id = 4,
                            MonthName = "April",
                            ProductID = 1,
                            SalesAmount = 1500m
                        },
                        new
                        {
                            Id = 5,
                            MonthName = "May",
                            ProductID = 1,
                            SalesAmount = 1600m
                        },
                        new
                        {
                            Id = 6,
                            MonthName = "June",
                            ProductID = 1,
                            SalesAmount = 1700m
                        },
                        new
                        {
                            Id = 7,
                            MonthName = "July",
                            ProductID = 1,
                            SalesAmount = 1800m
                        },
                        new
                        {
                            Id = 8,
                            MonthName = "August",
                            ProductID = 1,
                            SalesAmount = 1900m
                        },
                        new
                        {
                            Id = 9,
                            MonthName = "September",
                            ProductID = 1,
                            SalesAmount = 2000m
                        },
                        new
                        {
                            Id = 10,
                            MonthName = "October",
                            ProductID = 1,
                            SalesAmount = 2100m
                        },
                        new
                        {
                            Id = 11,
                            MonthName = "November",
                            ProductID = 1,
                            SalesAmount = 2200m
                        },
                        new
                        {
                            Id = 12,
                            MonthName = "December",
                            ProductID = 1,
                            SalesAmount = 2300m
                        },
                        new
                        {
                            Id = 13,
                            MonthName = "January",
                            ProductID = 2,
                            SalesAmount = 1400m
                        },
                        new
                        {
                            Id = 14,
                            MonthName = "February",
                            ProductID = 2,
                            SalesAmount = 1500m
                        },
                        new
                        {
                            Id = 15,
                            MonthName = "March",
                            ProductID = 2,
                            SalesAmount = 1600m
                        },
                        new
                        {
                            Id = 16,
                            MonthName = "April",
                            ProductID = 2,
                            SalesAmount = 1700m
                        },
                        new
                        {
                            Id = 17,
                            MonthName = "May",
                            ProductID = 2,
                            SalesAmount = 1800m
                        },
                        new
                        {
                            Id = 18,
                            MonthName = "June",
                            ProductID = 2,
                            SalesAmount = 1900m
                        },
                        new
                        {
                            Id = 19,
                            MonthName = "July",
                            ProductID = 2,
                            SalesAmount = 2000m
                        },
                        new
                        {
                            Id = 20,
                            MonthName = "August",
                            ProductID = 2,
                            SalesAmount = 2100m
                        },
                        new
                        {
                            Id = 21,
                            MonthName = "September",
                            ProductID = 2,
                            SalesAmount = 2200m
                        },
                        new
                        {
                            Id = 22,
                            MonthName = "October",
                            ProductID = 2,
                            SalesAmount = 2300m
                        },
                        new
                        {
                            Id = 23,
                            MonthName = "November",
                            ProductID = 2,
                            SalesAmount = 2400m
                        },
                        new
                        {
                            Id = 24,
                            MonthName = "December",
                            ProductID = 2,
                            SalesAmount = 2500m
                        },
                        new
                        {
                            Id = 25,
                            MonthName = "January",
                            ProductID = 3,
                            SalesAmount = 1600m
                        },
                        new
                        {
                            Id = 26,
                            MonthName = "February",
                            ProductID = 3,
                            SalesAmount = 1700m
                        },
                        new
                        {
                            Id = 27,
                            MonthName = "March",
                            ProductID = 3,
                            SalesAmount = 1800m
                        },
                        new
                        {
                            Id = 28,
                            MonthName = "April",
                            ProductID = 3,
                            SalesAmount = 1900m
                        },
                        new
                        {
                            Id = 29,
                            MonthName = "May",
                            ProductID = 3,
                            SalesAmount = 2000m
                        },
                        new
                        {
                            Id = 30,
                            MonthName = "June",
                            ProductID = 3,
                            SalesAmount = 2100m
                        },
                        new
                        {
                            Id = 31,
                            MonthName = "July",
                            ProductID = 3,
                            SalesAmount = 2200m
                        },
                        new
                        {
                            Id = 32,
                            MonthName = "August",
                            ProductID = 3,
                            SalesAmount = 2300m
                        },
                        new
                        {
                            Id = 33,
                            MonthName = "September",
                            ProductID = 3,
                            SalesAmount = 2400m
                        },
                        new
                        {
                            Id = 34,
                            MonthName = "October",
                            ProductID = 3,
                            SalesAmount = 2500m
                        },
                        new
                        {
                            Id = 35,
                            MonthName = "November",
                            ProductID = 3,
                            SalesAmount = 2600m
                        },
                        new
                        {
                            Id = 36,
                            MonthName = "December",
                            ProductID = 3,
                            SalesAmount = 2700m
                        },
                        new
                        {
                            Id = 37,
                            MonthName = "January",
                            ProductID = 4,
                            SalesAmount = 1800m
                        },
                        new
                        {
                            Id = 38,
                            MonthName = "February",
                            ProductID = 4,
                            SalesAmount = 1900m
                        },
                        new
                        {
                            Id = 39,
                            MonthName = "March",
                            ProductID = 4,
                            SalesAmount = 2000m
                        },
                        new
                        {
                            Id = 40,
                            MonthName = "April",
                            ProductID = 4,
                            SalesAmount = 2100m
                        },
                        new
                        {
                            Id = 41,
                            MonthName = "May",
                            ProductID = 4,
                            SalesAmount = 2200m
                        },
                        new
                        {
                            Id = 42,
                            MonthName = "June",
                            ProductID = 4,
                            SalesAmount = 2300m
                        },
                        new
                        {
                            Id = 43,
                            MonthName = "July",
                            ProductID = 4,
                            SalesAmount = 2400m
                        },
                        new
                        {
                            Id = 44,
                            MonthName = "August",
                            ProductID = 4,
                            SalesAmount = 2500m
                        },
                        new
                        {
                            Id = 45,
                            MonthName = "September",
                            ProductID = 4,
                            SalesAmount = 2600m
                        },
                        new
                        {
                            Id = 46,
                            MonthName = "October",
                            ProductID = 4,
                            SalesAmount = 2700m
                        },
                        new
                        {
                            Id = 47,
                            MonthName = "November",
                            ProductID = 4,
                            SalesAmount = 2800m
                        },
                        new
                        {
                            Id = 48,
                            MonthName = "December",
                            ProductID = 4,
                            SalesAmount = 2900m
                        },
                        new
                        {
                            Id = 49,
                            MonthName = "January",
                            ProductID = 5,
                            SalesAmount = 2000m
                        },
                        new
                        {
                            Id = 50,
                            MonthName = "February",
                            ProductID = 5,
                            SalesAmount = 2100m
                        },
                        new
                        {
                            Id = 51,
                            MonthName = "March",
                            ProductID = 5,
                            SalesAmount = 2200m
                        },
                        new
                        {
                            Id = 52,
                            MonthName = "April",
                            ProductID = 5,
                            SalesAmount = 2300m
                        },
                        new
                        {
                            Id = 53,
                            MonthName = "May",
                            ProductID = 5,
                            SalesAmount = 2400m
                        },
                        new
                        {
                            Id = 54,
                            MonthName = "June",
                            ProductID = 5,
                            SalesAmount = 2500m
                        },
                        new
                        {
                            Id = 55,
                            MonthName = "July",
                            ProductID = 5,
                            SalesAmount = 2600m
                        },
                        new
                        {
                            Id = 56,
                            MonthName = "August",
                            ProductID = 5,
                            SalesAmount = 2700m
                        },
                        new
                        {
                            Id = 57,
                            MonthName = "September",
                            ProductID = 5,
                            SalesAmount = 2800m
                        },
                        new
                        {
                            Id = 58,
                            MonthName = "October",
                            ProductID = 5,
                            SalesAmount = 2900m
                        },
                        new
                        {
                            Id = 59,
                            MonthName = "November",
                            ProductID = 5,
                            SalesAmount = 3000m
                        },
                        new
                        {
                            Id = 60,
                            MonthName = "December",
                            ProductID = 5,
                            SalesAmount = 3100m
                        },
                        new
                        {
                            Id = 61,
                            MonthName = "January",
                            ProductID = 6,
                            SalesAmount = 2200m
                        },
                        new
                        {
                            Id = 62,
                            MonthName = "February",
                            ProductID = 6,
                            SalesAmount = 2300m
                        },
                        new
                        {
                            Id = 63,
                            MonthName = "March",
                            ProductID = 6,
                            SalesAmount = 2400m
                        },
                        new
                        {
                            Id = 64,
                            MonthName = "April",
                            ProductID = 6,
                            SalesAmount = 2500m
                        },
                        new
                        {
                            Id = 65,
                            MonthName = "May",
                            ProductID = 6,
                            SalesAmount = 2600m
                        },
                        new
                        {
                            Id = 66,
                            MonthName = "June",
                            ProductID = 6,
                            SalesAmount = 2700m
                        },
                        new
                        {
                            Id = 67,
                            MonthName = "July",
                            ProductID = 6,
                            SalesAmount = 2800m
                        },
                        new
                        {
                            Id = 68,
                            MonthName = "August",
                            ProductID = 6,
                            SalesAmount = 2900m
                        },
                        new
                        {
                            Id = 69,
                            MonthName = "September",
                            ProductID = 6,
                            SalesAmount = 3000m
                        },
                        new
                        {
                            Id = 70,
                            MonthName = "October",
                            ProductID = 6,
                            SalesAmount = 3100m
                        },
                        new
                        {
                            Id = 71,
                            MonthName = "November",
                            ProductID = 6,
                            SalesAmount = 3200m
                        },
                        new
                        {
                            Id = 72,
                            MonthName = "December",
                            ProductID = 6,
                            SalesAmount = 3300m
                        });
                });

            modelBuilder.Entity("Blazor26.Models.Models.Product", b =>
                {
                    b.HasOne("Blazor26.Models.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Blazor26.Models.Models.Sales", b =>
                {
                    b.HasOne("Blazor26.Models.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Blazor26.Models.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
